### ISSUE TITLE
Allow third party download.

### ISSUE THREAD

**Issue by drakosoldier298** [Skylortrexler/SkyLib#3]
![image](https://user-images.githubusercontent.com/30358222/178088898-eef02cd0-0984-40b8-b2af-91b3ba089603.png)
This toggle allows polymc/multimc and other non curseforge launchers to download your curseforge mod, aka no more forcing users to play on curseforge launcher

**Comment by drakosoldier298** [comment]
Its 2 buttons and you decided to ban a user for joining your discord. You are petty you make money off so many of your mods why not just let this happen to one of your mods.

**Comment by skylorbeck** [comment]
Holy Christ just go complain to curseforge.

**Comment by skylorbeck** [comment]
I really don't know how many times I have to say this. Complain to curseforge. They don't pay me for third party downloads. If you complain, it could make them change their mind and then we both win.
